### ISSUE TITLE
TODO before v1

### ISSUE THREAD

**Issue by ADejbakhsh** [ADejbakhsh/ean_gtin_getter#2]
- [ ] front end 
- [ ] - Front page
- [ ] - Login 
- [ ] - Payment 
- [ ] - Previous request result / logs
- [ ] - API documentation
<br>

- [ ] back end
- [ ] - Proxy request function
- [ ] - API key management
- [ ] - Database for user and payment
- [ ] --- User
- [ ] --- Payment
